FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
############################## SYSTEM PARAMETERS ##############################
# * Arguments
ARG USER=initial
ARG GROUP=initial
ARG UID=1000
ARG GID="${UID}"
ARG SHELL=/bin/bash
ARG HARDWARE=x86_64
ARG ENTRYPOINT_FILE=entrypint.sh

# * Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
# ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

# * Setup users and groups
RUN groupadd -g ${GID} ${USER} \
    && useradd -m -u ${UID} -g ${GID} -s ${SHELL} ${USER} \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    sudo \
    git \
    wget \
    vim \
    python3-pip \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER}


# * Replace apt urls
# ? Change to tku
RUN sed -i 's@archive.ubuntu.com@ftp.tku.edu.tw@g' /etc/apt/sources.list
# ? Change to Taiwan
# RUN sed -i 's@archive.ubuntu.com@tw.archive.ubuntu.com@g' /etc/apt/sources.list

# * Time zone
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/"${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone

# * Copy custom configuration
# ? Requires docker version >= 17.09
COPY --chmod=0775 ./${ENTRYPOINT_FILE} /entrypoint.sh
COPY --chown="${USER}":"${GROUP}" --chmod=0775 config config
# ? docker version < 17.09
# COPY ./${ENTRYPOINT_FILE} /entrypoint.sh
# COPY config config
# RUN sudo chmod 0775 /entrypoint.sh && \
# sudo chown -R "${USER}":"${GROUP}" config \
# && sudo chmod -R 0775 config

############################### INSTALL #######################################
# * Install packages
RUN apt update \
    && apt install -y --no-install-recommends \
    sudo \
    git \
    htop \
    wget \
    curl \
    psmisc \
    # * Shell
    tmux \
    nano \
    terminator \
    # * base tools
    udev \
    libtool \
    python3-pip \
    python3-dev \
    python3-setuptools \
    software-properties-common \
    lsb-release \
    libhidapi-dev \
    openssh-server \
    # * Work tools
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Install pip
RUN pip3 install --upgrade pip \
    && pip3 install setuptools \
    && pip3 install wheel \
    && pip3 install nvitop \
    && pip3 install notebook

# RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
# RUN sudo add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
# RUN rm -rf /etc/apt/source.list.d/ros2.list
RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(lsb_release -c | awk '{print $2}')_all.deb" && \
    dpkg -i /tmp/ros2-apt-source.deb && \
    rm /tmp/ros2-apt-source.deb
RUN apt update && apt install -y --no-install-recommends \
    python3-rosdep \
    ros-humble-desktop \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-diagnostic-updater \
    ros-humble-moveit \
    python3-colcon-common-extensions \
    v4l-utils \
    ffmpeg \
    ros-humble-ur \
    ros-humble-imu-tools \
    ros-humble-xacro \
    ros-humble-ros-testing \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE

# RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u

RUN mkdir -p /etc/apt/keyrings
RUN curl -sSf https://librealsense.realsenseai.com/Debian/librealsenseai.asc | \
    gpg --dearmor | sudo tee /etc/apt/keyrings/librealsenseai.gpg > /dev/null
RUN echo "deb [signed-by=/etc/apt/keyrings/librealsenseai.gpg] https://librealsense.realsenseai.com/Debian/apt-repo `lsb_release -cs` main" | \
    tee /etc/apt/sources.list.d/librealsense.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    librealsense2-utils \
    librealsense2-dev \
    librealsense2-udev-rules \
    ros-humble-librealsense2* \
    && apt-get clean && rm -rf /var/lib/apt/lists/*c


# RUN apt-get update && apt-get install -y --no-install-recommends \
#     v4l-utils \
#     ffmpeg \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     ros-humble-ur \
#     ros-humble-imu-tools \
#     ros-humble-xacro \
#     ros-humble-ros-testing \
#     && apt clean \
#     && rm -rf /var/lib/apt/lists/*

#################### Kinect Azure ###############################
RUN apt-get update && apt install -y \
    libgl1-mesa-dev libsoundio-dev libvulkan-dev libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev libusb-1.0-0-dev libssl-dev libudev-dev mesa-common-dev uuid-dev

WORKDIR /home/${USER}/work/azure
RUN wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/k/k4a-tools/k4a-tools_1.4.2_amd64.deb
RUN wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/libk4a1.4-dev/libk4a1.4-dev_1.4.2_amd64.deb
RUN wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/libk4a1.4/libk4a1.4_1.4.2_amd64.deb
RUN wget http://ftp.de.debian.org/debian/pool/main/libs/libsoundio/libsoundio1_1.1.0-1_amd64.deb

RUN ACCEPT_EULA=Y dpkg -i libk4a1.4_1.4.2_amd64.deb &&\
    dpkg -i libk4a1.4-dev_1.4.2_amd64.deb
RUN dpkg -i libsoundio1_1.1.0-1_amd64.deb
RUN dpkg -i k4a-tools_1.4.2_amd64.deb

RUN rm libk4a1.4_1.4.2_amd64.deb \
    libk4a1.4-dev_1.4.2_amd64.deb \
    libsoundio1_1.1.0-1_amd64.deb \
    k4a-tools_1.4.2_amd64.deb

WORKDIR /home/${USER}/work/azure
RUN git clone https://github.com/microsoft/Azure-Kinect-Sensor-SDK.git
WORKDIR /home/${USER}/work/azure/Azure-Kinect-Sensor-SDK
RUN mkdir -p /etc/udev/rules.d/ && \
    cp ./scripts/99-k4a.rules /etc/udev/rules.d/

RUN rm -rf /home/${USER}/work/azure/Azure-Kinect-Sensor-SDK

#################### Kinect Azure ###############################

############################## USER CONFIG ####################################

# * Switch user to ${USER}
USER ${USER}
WORKDIR /
RUN curl -fsSL https://opencode.ai/install | bash
RUN curl -fsSL https://claude.ai/install.sh | bash
RUN echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc

RUN ./config/shell/bash_setup.sh "${USER}" "${GROUP}" \
    && ./config/shell/terminator/terminator_setup.sh "${USER}" "${GROUP}" \
    && ./config/shell/tmux/tmux_setup.sh "${USER}" "${GROUP}"
    # && sudo rm -rf /config
RUN export CXX=g++
RUN export MAKEFLAGS="-j nproc"
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc

# * Switch workspace to ~/work
RUN mkdir -p /home/"${USER}"/work
WORKDIR /home/"${USER}"/work

# COPY lerobot_pyproject.toml .
# COPY gr00t_pyproject.toml .

#lerobot env
# RUN git clone https://github.com/huggingface/lerobot.git && \
#     cd lerobot && \
#     pip3 install -e .
# COPY ../ur5e_data_collect_ws/Isaac-GR00T/ /home/"${USER}"/work/Isaac-GR00T/
WORKDIR /home/"${USER}"/work/pkgs
# RUN git clone https://github.com/NVIDIA/Isaac-GR00T && \
#     cd Isaac-GR00T && \
#     pip3 install -e .[base]
RUN pip3 install torch==2.7.0 torchvision==0.22.0 --index-url https://download.pytorch.org/whl/cu128
RUN pip3 install --no-build-isolation flash-attn==2.8.3


RUN sudo apt update && sudo apt install unzip
RUN  wget https://github.com/huggingface/lerobot/archive/refs/tags/v0.3.3.zip -O lerobot.zip \
    && unzip lerobot.zip \
    && rm lerobot.zip \
    # Rename the extracted folder (it’s usually like yourrepo-1.2.3)
    && mv lerobot-0.3.3/ lerobot

RUN cd lerobot && \
    pip3 install -e .

#RUN echo "export PYTHONPATH="/home/${USER}/work/pkgs/lerobot:${PYTHONPATH}"" >> ~/.bashrc

WORKDIR /home/"${USER}"/work

RUN pip3 install avp_stream --no-deps
RUN pip3 install grpcio
RUN pip3 install numpy==1.26.4

WORKDIR /
RUN ./config/pip/pip_setup.sh


# * Make SSH available
EXPOSE 22

ENTRYPOINT [ "/entrypoint.sh", "terminator" ]
# ENTRYPOINT [ "/entrypoint.sh", "tmux" ]
# ENTRYPOINT [ "/entrypoint.sh", "bash" ]
# ENTRYPOINT [ "/entrypoint.sh" ]
